name: Testing

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-base:
    name: Test base version
    runs-on: ubuntu-latest
    env:
      TEST_ENV: CI
      SKIP_CLI_TEST: "1"
    steps:
      - uses: actions/checkout@v7
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: 3.14
      - name: Install the project
        run: uv sync --no-group dev --no-group doc --no-cache --extra visualization
      - name: pytest
        run: |
          uv run --no-group dev --no-group doc --extra visualization pytest
  test-all:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
        python-version:
          - "3.14"
          - "3.13"
    env:
      TEST_ENV: CI
    steps:
      - uses: actions/checkout@v7
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --no-group dev --no-group doc --all-extras --no-cache
      - name: pytest
        run: |
          uv run --no-group dev --no-group doc pytest -v --cov-report term-missing --cov=gpx_track_analyzer
